Feature/crm 4330 extapi link ticket to schedule
hokan-inc/hokan_api_document pull request #13
Opened 2022-01-31 09:27 UTC by shuchan3362

2022-01-31 14:10 UTC, tomohidemiya commented on spec/components/schemas/projects/tickets/base_ticket.yaml
> +      スケジュールIDを指定した場合、既存のスケジュールと紐づきます。
ここ改行します？

2022-01-31 14:13 UTC, tomohidemiya requested changes
修正お願いします

2022-01-31 14:13 UTC, tomohidemiya commented on spec/components/schemas/projects/tickets/base_ticket.yaml
> +      "
ユーザーに見せるものについては不明瞭な振る舞いをする場合の条件を必ず記載するようにしてください。
この場合、下記はユーザーにとって予期しないので、少なくともここで明記しましょう。
* スケジュールIDが存在しないものを指定した場合はエラー
* 他のcustomer_idが設定されている場合は無視される

2022-01-31 14:16 UTC, shuchan3362 commented on spec/components/schemas/projects/tickets/base_ticket.yaml
> +      スケジュールIDを指定した場合、既存のスケジュールと紐づきます。
改行します！

2022-01-31 14:22 UTC, shuchan3362 commented on spec/components/schemas/projects/tickets/base_ticket.yaml
> +      "
e65c103b3a4775b74c90e19c55ba6a878555d983
こちらで修正しました！

2022-01-31 14:22 UTC, shuchan3362 commented on spec/components/schemas/projects/tickets/base_ticket.yaml
> +      スケジュールIDを指定した場合、既存のスケジュールと紐づきます。
e65c103b3a4775b74c90e19c55ba6a878555d983

2022-01-31 14:30 UTC, tomohidemiya approved these changes

2022-02-02 09:29 UTC, shuchan3362 commented
@tomohidemiya @donaisore 
こちらも修正したので確認お願いしたいです！

2022-02-02 10:31 UTC, donaisore approved these changes

2022-02-02 11:50 UTC, tomohidemiya approved these changes

2022-02-02 14:02 UTC, merged