feature/CRM-3251_retrieve_customer
hokan-inc/hokan_api_document pull request #6
Opened 2021-09-22 07:29 UTC by kawahito25

2021-09-22 08:44 UTC, Cohey0727 requested changes

2021-09-22 08:44 UTC, Cohey0727 commented on spec/components/responses/customer/200.yaml
> +description: 200 response
このdirectory構成だとcustomerの一覧か詳細か、GET、POST、PUT、DELETEかの区別がつかないと思いますがどうですか？

2021-09-24 02:37 UTC, kawahito25 commented on spec/components/responses/customer/200.yaml
> +description: 200 response
冗長に書きました。

2021-09-24 05:20 UTC, kawahito25 commented on spec/components/schemas/customers/common_customer.yaml
> -  - $ref: "../common/extra_values.yaml"
ここに差分が出るの謎ですね・・w

2021-09-24 06:33 UTC, Cohey0727 commented
LGTM
2021/09/29でリリースします。

2021-10-13 02:45 UTC, merged