Feature/crm 2950 ticket
hokan-inc/hokan_api_document pull request #8
Opened 2021-12-08 06:42 UTC by hkoichi

2021-12-08 06:42 UTC, hkoichi commented on spec/paths/projects/ticket.yaml
> +                - $ref: "../../components/schemas/projects/tickets/other_ticket.yaml"
各 ref に名前がつけられないのが問題

2021-12-09 01:49 UTC, Cohey0727 commented on spec/paths/projects/ticket.yaml
> +                - $ref: "../../components/schemas/projects/tickets/other_ticket.yaml"
@donaisore 
これなんか回避策的なの探ってませんでしたっけ？

2021-12-09 01:53 UTC, donaisore commented on spec/paths/projects/ticket.yaml
> +                - $ref: "../../components/schemas/projects/tickets/other_ticket.yaml"
「探っていたが、イマイチ見つけられていない」ということを昨日はせやんさんにお伝えしました！
で、修正したものを今commitしていただいているようです！

![image](https://user-images.githubusercontent.com/33693745/145319959-c9271180-97b3-49f5-a4a4-ac5d3fcaf2de.png)

2021-12-10 01:46 UTC, donaisore requested changes

2021-12-10 01:46 UTC, donaisore commented on spec/components/schemas/projects/tickets/policy_maturity_ticket.yaml
> +          チケットに紐付ける更改前契約IDのリスト。<br>
`のリスト` という文言だけ不要かなと 🙏

2021-12-10 01:46 UTC, donaisore commented on spec/components/schemas/projects/tickets/accident_ticket.yaml
> +          チケットに紐付ける契約IDのリスト。<br>
`のリスト` という文言だけ不要かなと 🙏

2021-12-15 09:21 UTC, merged